WALG_COMPRESSION_METHOD: brotli
CLONE_WALG_COMPRESSION_METHOD: brotli
USE_WALG_RESTORE: 'true'
CLONE_USE_WALG_RESTORE: 'true'
USE_WALG_BACKUP: 'true'
CLONE_USE_WALG_BACKUP: 'true'
BACKUP_SCHEDULE: "0 * * * *"
CLONE_BACKUP_SCHEDULE: "0 * * * *"
BACKUP_NUM_TO_RETAIN: "5"
CLONE_BACKUP_NUM_TO_RETAIN: "5"
WAL_BUCKET_SCOPE_SUFFIX: ""
CLONE_WAL_BUCKET_SCOPE_SUFFIX: ""
LOG_BUCKET_SCOPE_SUFFIX: ""
CLONE_LOG_BUCKET_SCOPE_SUFFIX: ""
AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
CLONE_AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
CLONE_AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
AWS_REGION: "eu-north-1"
CLONE_AWS_REGION: "eu-north-1"
WALG_S3_PREFIX: "s3://<bucket-name>"
CLONE_WALG_S3_PREFIX: "s3://<bucket-name>"
CLONE_METHOD: CLONE_WITH_WALG